### ISSUE TITLE
Lots o' Issues

### ISSUE THREAD

**Issue by TheIttim** [ZiplineProject/zipline#18]
So, current issues. Can't Update User(had to use Postman to fix the POST request), Shortened URLs don't work, Hitting Enter in URL textbox relocates you to Home Page, No way to Delete Images.

**Comment by TheIttim** [comment]
Can't Update User:
Login > In `Update Your Profile` type in new user/pass > hit enter > Error Messeage appears.
Shortened URLs 
Submit URL to be shortened, try to use shortened URL > 404 error appears(example: https://cdn.ittim.xyz/s/nnxA)
Hitting Enter in URL textbox relocates you to Home Page
Click URL shortener textbox > click enter > get yeeted to Home Page
No Way to Delete Images
Go to Images Tab > Have a midlife crisis at 20.

**Comment by dicedtomatoreal** [comment]
After trying to recreate all of these here is my response:
1. updating user: yep, this is a problem, it is due to the current user being "null". This is now fixed, an update should be coming out soon with some more updates.
2. shortening urls: This does not happen to me, I did exactly what you did but i didnt get a 404 error.
3. Shortening urls pressing enter: Pressing enter is not supposed to be done as it was never meant to be actual functionality. This will not be added.
4. Deleting Imgs: This is on purpose, a later update will be coming out with this!
